### ISSUE TITLE
Request: Adjust Kerning for Selected Glyph(s)

### ISSUE THREAD

**Issue by gorjious** [mekkablue/Glyphs-Scripts#255]
Discovering the usefulness of the Adjust Kerning script to quickly change a large number of pairs. I am finding this helpful if I need to make adjustments to the spacing after kerning. For example: if I increase the RSB of a glyph by +10 then with Adjust Kerning I can reduce all the pairs that are already kerned by -10 so it balances back. 
 
Currently, Adjust Kerning applies to both left and right sides across all pairs in the master. 
The request would be to add extra control:
1) being able to specify which glyph(s) and subsequent pairs would receive the adjustment. this can be by initial selection.
2) being able to specify which side the adjustment (+ - * /) will be applied to. 

Perhaps with an option to open a new tab with all the affected pairs.

**Comment by mekkablue** [comment]
Bwoah. I am afraid this cannot be satisfactorily solved within the scope of this script. There is a principal logical problem:

1. Kerning values do not belong to a certain glyph, but pairs. IOW there is no such thing as the ‘kerning of a glyph.’ To make things worse, it is pairs of glyphs or pairs of _groups._ And this is where it becomes impossible to only adjust the kerning of the left side of `e`, because it may be (and very likely is) in a kerning group with other glyphs. This leads to the dilemma where you either adjust and mess up the kerning for other glyphs, or you don't adjust.
2. A kerning value has no side. But the script adjusts kerning values.

The scenarios you describe are highly complex and are better sorted out manually in the Kerning panel, with the proper filters applied.
